### PR TITLE
Create readme

### PR DESCRIPTION
**Pull request by billfreeman44**
see how this looks -> https://github.com/billfreeman44/demoScrape2/tree/create-readme

### CODE REVIEW

**Comment by billfreeman44** [comment]
@cokenyo pls can has merge?

**Comment by cokenyo** [comment]
We may want to include the source library. I believe there may be a couple lines the needed to be run in console?

**Comment by cokenyo** [comment]
@billfreeman44

**Comment by billfreeman44** [comment]
> We may want to include the source library. I believe there may be a couple lines the needed to be run in console?

I might've had the library installed from before. I'm not sure. I think go auto-installs things though.

**Comment by billfreeman44** [comment]
I tested these instructions with nightfury and they work as-is.  If we want to fully include the csgo parser binary I think we can do so in a separate PR. @cokenyo

**Pull request merged**
